image:
  file: .gitpod.dockerfile

  tasks:
    - name: create schema
        command: "mysql  < db/schema.sql"



#ports:
#  - port: 8080
#    onOpen: open-preview
#  - port: 3306
#    onOpen: open-preview

