image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      ./mvnw package dockerfile:build -DskipTests=true -Ddockerfile.skip=true
    command: |
      mysql < db/schema.sql

ports:
  - port: 8080
    onOpen: open-preview
  - port: 2375
    onOpen: ignore
  - port: 3306
    onOpen: ignore


